# Copyright (c) Meta Platforms, Inc. and affiliates.
ROOT_NAME = "body_world"
HIPS_NAME = "b_root"
NECK_NAME = "b_neck0"
HEAD_NAME = "b_head"
SPINE0_NAME = "b_spine0"
SPINE1_NAME = "b_spine1"
SPINE2_NAME = "b_spine2"
SPINE3_NAME = "b_spine3"

# Left arm bones
LEFT_SCAP_NAME = "p_l_scap"
LEFT_SHOULDER_NAME = "b_l_shoulder"
LEFT_ARM_NAME = "b_l_arm"
LEFT_ELBOW_NAME = "b_l_forearm"
LEFT_WRIST_TWIST_NAME = "b_l_wrist_twist"
LEFT_WRIST_NAME = "b_l_wrist"

# Right arm bones
RIGHT_SCAP_NAME = "p_r_scap"
RIGHT_SHOULDER_NAME = "b_r_shoulder"
RIGHT_ARM_NAME = "b_r_arm"
RIGHT_ELBOW_NAME = "b_r_forearm"
RIGHT_WRIST_TWIST_NAME = "b_r_wrist_twist"
RIGHT_WRIST_NAME = "b_r_wrist"

# Left leg bones
LEFT_HIP_NAME = "b_l_upleg"
LEFT_KNEE_NAME = "b_l_leg"
LEFT_FOOT_TWIST_NAME = "b_l_foot_twist"
LEFT_ANKLE_NAME = "b_l_talocrural"
LEFT_HEEL1_NAME = "b_l_subtalar"
LEFT_HEEL2_NAME = "b_l_transversetarsal"
LEFT_BALL_NAME = "b_l_ball"

# Right leg bones
RIGHT_HIP_NAME = "b_r_upleg"
RIGHT_KNEE_NAME = "b_r_leg"
RIGHT_FOOT_TWIST_NAME = "b_r_foot_twist"
RIGHT_ANKLE_NAME = "b_r_talocrural"
RIGHT_HEEL1_NAME = "b_r_subtalar"
RIGHT_HEEL2_NAME = "b_r_transversetarsal"
RIGHT_BALL_NAME = "b_r_ball"

# Left hand bones
LEFT_THUMB0_NAME = "b_l_thumb0"
LEFT_THUMB1_NAME = "b_l_thumb1"
LEFT_THUMB2_NAME = "b_l_thumb2"
LEFT_THUMB3_NAME = "b_l_thumb3"
LEFT_THUMB_NULL_NAME = "b_l_thumb_null"

LEFT_INDEX1_NAME = "b_l_index1"
LEFT_INDEX2_NAME = "b_l_index2"
LEFT_INDEX3_NAME = "b_l_index3"
LEFT_INDEX_NULL_NAME = "b_l_index_null"

LEFT_MIDDLE1_NAME = "b_l_middle1"
LEFT_MIDDLE2_NAME = "b_l_middle2"
LEFT_MIDDLE3_NAME = "b_l_middle3"
LEFT_MIDDLE_NULL_NAME = "b_l_middle_null"

LEFT_RING1_NAME = "b_l_ring1"
LEFT_RING2_NAME = "b_l_ring2"
LEFT_RING3_NAME = "b_l_ring3"
LEFT_RING_NULL_NAME = "b_l_ring_null"

LEFT_PINKY1_NAME = "b_l_pinky1"
LEFT_PINKY2_NAME = "b_l_pinky2"
LEFT_PINKY3_NAME = "b_l_pinky3"
LEFT_PINKY_NULL_NAME = "b_l_pinky_null"

# Right hand bones
RIGHT_THUMB0_NAME = "b_r_thumb0"
RIGHT_THUMB1_NAME = "b_r_thumb1"
RIGHT_THUMB2_NAME = "b_r_thumb2"
RIGHT_THUMB3_NAME = "b_r_thumb3"
RIGHT_THUMB_NULL_NAME = "b_r_thumb_null"

RIGHT_INDEX1_NAME = "b_r_index1"
RIGHT_INDEX2_NAME = "b_r_index2"
RIGHT_INDEX3_NAME = "b_r_index3"
RIGHT_INDEX_NULL_NAME = "b_r_index_null"

RIGHT_MIDDLE1_NAME = "b_r_middle1"
RIGHT_MIDDLE2_NAME = "b_r_middle2"
RIGHT_MIDDLE3_NAME = "b_r_middle3"
RIGHT_MIDDLE_NULL_NAME = "b_r_middle_null"

RIGHT_RING1_NAME = "b_r_ring1"
RIGHT_RING2_NAME = "b_r_ring2"
RIGHT_RING3_NAME = "b_r_ring3"
RIGHT_RING_NULL_NAME = "b_r_ring_null"

RIGHT_PINKY1_NAME = "b_r_pinky1"
RIGHT_PINKY2_NAME = "b_r_pinky2"
RIGHT_PINKY3_NAME = "b_r_pinky3"
RIGHT_PINKY_NULL_NAME = "b_r_pinky_null"

LAYERING_NAMES = [
    HEAD_NAME,
    LEFT_ELBOW_NAME,
    LEFT_WRIST_NAME,
    RIGHT_ELBOW_NAME,
    RIGHT_WRIST_NAME,
    HIPS_NAME,
    LEFT_KNEE_NAME,
    LEFT_BALL_NAME,
    RIGHT_KNEE_NAME,
    RIGHT_BALL_NAME,
]

FULL_BODY_NAMES = [
    HIPS_NAME,
    LEFT_HIP_NAME,
    LEFT_KNEE_NAME,
    LEFT_ANKLE_NAME,
    LEFT_BALL_NAME,
    RIGHT_HIP_NAME,
    RIGHT_KNEE_NAME,
    RIGHT_ANKLE_NAME,
    RIGHT_BALL_NAME,
    SPINE0_NAME,
    SPINE1_NAME,
    SPINE2_NAME,
    SPINE3_NAME,
    NECK_NAME,
    HEAD_NAME,
    LEFT_SHOULDER_NAME,
    LEFT_ARM_NAME,
    LEFT_ELBOW_NAME,
    LEFT_WRIST_NAME,
    RIGHT_SHOULDER_NAME,
    RIGHT_ARM_NAME,
    RIGHT_ELBOW_NAME,
    RIGHT_WRIST_NAME,
]

FULL_BODY_PARENT_NAMES = [
    None,
    HIPS_NAME,
    LEFT_HIP_NAME,
    LEFT_KNEE_NAME,
    LEFT_ANKLE_NAME,
    HIPS_NAME,
    RIGHT_HIP_NAME,
    RIGHT_KNEE_NAME,
    RIGHT_ANKLE_NAME,
    HIPS_NAME,
    SPINE0_NAME,
    SPINE1_NAME,
    SPINE2_NAME,
    SPINE3_NAME,
    NECK_NAME,
    SPINE3_NAME,
    LEFT_SHOULDER_NAME,
    LEFT_ARM_NAME,
    LEFT_ELBOW_NAME,
    SPINE3_NAME,
    RIGHT_SHOULDER_NAME,
    RIGHT_ARM_NAME,
    RIGHT_ELBOW_NAME,
]

LOWER_BODY_NAMES = [
    HIPS_NAME,
    LEFT_HIP_NAME,
    LEFT_KNEE_NAME,
    LEFT_ANKLE_NAME,
    LEFT_BALL_NAME,
    RIGHT_HIP_NAME,
    RIGHT_KNEE_NAME,
    RIGHT_ANKLE_NAME,
    RIGHT_BALL_NAME,
]

LOWER_BODY_PARENT_NAMES = [
    None,
    HIPS_NAME,
    LEFT_HIP_NAME,
    LEFT_KNEE_NAME,
    LEFT_ANKLE_NAME,
    HIPS_NAME,
    RIGHT_HIP_NAME,
    RIGHT_KNEE_NAME,
    RIGHT_ANKLE_NAME,
]

UPPER_BODY_NAMES = [
    HIPS_NAME,
    SPINE0_NAME,
    SPINE1_NAME,
    SPINE2_NAME,
    SPINE3_NAME,
    NECK_NAME,
    HEAD_NAME,
    LEFT_SHOULDER_NAME,
    LEFT_ARM_NAME,
    LEFT_ELBOW_NAME,
    LEFT_WRIST_NAME,
    RIGHT_SHOULDER_NAME,
    RIGHT_ARM_NAME,
    RIGHT_ELBOW_NAME,
    RIGHT_WRIST_NAME,
]

UPPER_BODY_PARENT_NAMES = [
    None,
    HIPS_NAME,
    SPINE0_NAME,
    SPINE1_NAME,
    SPINE2_NAME,
    SPINE3_NAME,
    NECK_NAME,
    SPINE3_NAME,
    LEFT_SHOULDER_NAME,
    LEFT_ARM_NAME,
    LEFT_ELBOW_NAME,
    SPINE3_NAME,
    RIGHT_SHOULDER_NAME,
    RIGHT_ARM_NAME,
    RIGHT_ELBOW_NAME,
]

LEFT_HAND_NAMES = [
    LEFT_THUMB0_NAME,
    LEFT_THUMB1_NAME,
    LEFT_THUMB2_NAME,
    LEFT_THUMB3_NAME,
    LEFT_INDEX1_NAME,
    LEFT_INDEX2_NAME,
    LEFT_INDEX3_NAME,
    LEFT_MIDDLE1_NAME,
    LEFT_MIDDLE2_NAME,
    LEFT_MIDDLE3_NAME,
    LEFT_RING1_NAME,
    LEFT_RING2_NAME,
    LEFT_RING3_NAME,
    LEFT_PINKY1_NAME,
    LEFT_PINKY2_NAME,
    LEFT_PINKY3_NAME,
]

LEFT_HAND_PARENT_NAMES = [
    LEFT_WRIST_NAME,
    LEFT_THUMB0_NAME,
    LEFT_THUMB1_NAME,
    LEFT_THUMB2_NAME,
    LEFT_WRIST_NAME,
    LEFT_INDEX1_NAME,
    LEFT_INDEX2_NAME,
    LEFT_WRIST_NAME,
    LEFT_MIDDLE1_NAME,
    LEFT_MIDDLE2_NAME,
    LEFT_WRIST_NAME,
    LEFT_RING1_NAME,
    LEFT_RING2_NAME,
    LEFT_WRIST_NAME,
    LEFT_PINKY1_NAME,
    LEFT_PINKY2_NAME,
]

RIGHT_HAND_NAMES = [
    RIGHT_THUMB0_NAME,
    RIGHT_THUMB1_NAME,
    RIGHT_THUMB2_NAME,
    RIGHT_THUMB3_NAME,
    RIGHT_INDEX1_NAME,
    RIGHT_INDEX2_NAME,
    RIGHT_INDEX3_NAME,
    RIGHT_MIDDLE1_NAME,
    RIGHT_MIDDLE2_NAME,
    RIGHT_MIDDLE3_NAME,
    RIGHT_RING1_NAME,
    RIGHT_RING2_NAME,
    RIGHT_RING3_NAME,
    RIGHT_PINKY1_NAME,
    RIGHT_PINKY2_NAME,
    RIGHT_PINKY3_NAME,
]

RIGHT_HAND_PARENT_NAMES = [
    RIGHT_WRIST_NAME,
    RIGHT_THUMB0_NAME,
    RIGHT_THUMB1_NAME,
    RIGHT_THUMB2_NAME,
    RIGHT_WRIST_NAME,
    RIGHT_INDEX1_NAME,
    RIGHT_INDEX2_NAME,
    RIGHT_WRIST_NAME,
    RIGHT_MIDDLE1_NAME,
    RIGHT_MIDDLE2_NAME,
    RIGHT_WRIST_NAME,
    RIGHT_RING1_NAME,
    RIGHT_RING2_NAME,
    RIGHT_WRIST_NAME,
    RIGHT_PINKY1_NAME,
    RIGHT_PINKY2_NAME,
]
FULL_BODY_NAMES_WITH_HANDS = [*FULL_BODY_NAMES, *LEFT_HAND_NAMES, *RIGHT_HAND_NAMES]
FULL_BODY_PARENT_NAMES_WITH_HANDS = [
    *FULL_BODY_PARENT_NAMES,
    *LEFT_HAND_PARENT_NAMES,
    *RIGHT_HAND_PARENT_NAMES,
]
